<?php

declare(strict_types=1);

use App\Http\Controllers\Api\V1\AliExpressCookiesController;
use App\Http\Controllers\Api\V1\DatabaseBackupCreateController;
use App\Http\Controllers\Api\V1\DatabaseBackupIndexController;
use App\Http\Controllers\Api\V1\DatabaseBackupRestoreController;
use App\Http\Controllers\Api\V1\EmployeeInventoryCountController;
use App\Http\Controllers\Api\V1\ExternalAccessShowController;
use App\Http\Controllers\Api\V1\ExternalAccessUpdateController;
use App\Http\Controllers\Api\V1\ExternalRateLimitShowController;
use App\Http\Controllers\Api\V1\ExternalRateLimitUpdateController;
use App\Http\Controllers\Api\V1\InventoryCheckApplyController;
use App\Http\Controllers\Api\V1\InventoryCheckDeleteController;
use App\Http\Controllers\Api\V1\InventoryCheckDownloadController;
use App\Http\Controllers\Api\V1\InventoryCheckImportController;
use App\Http\Controllers\Api\V1\InventoryCheckIndexController;
use App\Http\Controllers\Api\V1\InventoryCheckItemUpdateController;
use App\Http\Controllers\Api\V1\InventoryCheckShowController;
use App\Http\Controllers\Api\V1\JobBatchCancelController;
use App\Http\Controllers\Api\V1\JobBatchIndexController;
use App\Http\Controllers\Api\V1\JobBatchItemsController;
use App\Http\Controllers\Api\V1\JobBatchResumeController;
use App\Http\Controllers\Api\V1\JobBatchShowController;
use App\Http\Controllers\Api\V1\LatestProductCostsRefreshController;
use App\Http\Controllers\Api\V1\MaintenanceNoteController;
use App\Http\Controllers\Api\V1\MaintenanceNoteUpsertController;
use App\Http\Controllers\Api\V1\PriceResearchFilterOptionsController;
use App\Http\Controllers\Api\V1\PriceResearchProductsController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteMaintenanceController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteReportHandledController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteReportsController;
use App\Http\Controllers\Api\V1\PriceResearchRunController;
use App\Http\Controllers\Api\V1\PriceResearchRunLogsController;
use App\Http\Controllers\Api\V1\PriceResearchRunMaintenanceController;
use App\Http\Controllers\Api\V1\PriceResearchRunStatusController;
use App\Http\Controllers\Api\V1\ProductAvailableController;
use App\Http\Controllers\Api\V1\ProductBarcodeController;
use App\Http\Controllers\Api\V1\ProductBulkArchiveController;
use App\Http\Controllers\Api\V1\ProductBulkDeleteController;
use App\Http\Controllers\Api\V1\ProductBulkPlamodAssetRenameController;
use App\Http\Controllers\Api\V1\ProductBulkUpdateController;
use App\Http\Controllers\Api\V1\ProductExternalAssetDestroyController;
use App\Http\Controllers\Api\V1\ProductExternalAssetDownloadController;
use App\Http\Controllers\Api\V1\ProductExternalAssetShopifyEnabledController;
use App\Http\Controllers\Api\V1\ProductExternalAssetViewController;
use App\Http\Controllers\Api\V1\ProductFilledController;
use App\Http\Controllers\Api\V1\ProductFilterOptionsController;
use App\Http\Controllers\Api\V1\ProductHandleImportController;
use App\Http\Controllers\Api\V1\ProductImageAssetOrderController;
use App\Http\Controllers\Api\V1\ProductImportController;
use App\Http\Controllers\Api\V1\ProductInfoShowController;
use App\Http\Controllers\Api\V1\ProductInfoSyncController;
use App\Http\Controllers\Api\V1\ProductInventoryImportController;
use App\Http\Controllers\Api\V1\ProductInventoryQuantityOverrideImportController;
use App\Http\Controllers\Api\V1\ProductLatestArrivalController;
use App\Http\Controllers\Api\V1\ProductMaintainController;
use App\Http\Controllers\Api\V1\ProductMaintenanceController;
use App\Http\Controllers\Api\V1\ProductManualImageUploadController;
use App\Http\Controllers\Api\V1\ProductMissingInfoSyncController;
use App\Http\Controllers\Api\V1\ProductPlamodAssetOrderController;
use App\Http\Controllers\Api\V1\ProductPlamodShowController;
use App\Http\Controllers\Api\V1\ProductPlamodSyncController;
use App\Http\Controllers\Api\V1\ProductPoLinesController;
use App\Http\Controllers\Api\V1\ProductPreferredDescriptionSourceController;
use App\Http\Controllers\Api\V1\ProductReadyController;
use App\Http\Controllers\Api\V1\ProductReplenishmentExportController;
use App\Http\Controllers\Api\V1\ProductReplenishmentPreviewController;
use App\Http\Controllers\Api\V1\ProductsController;
use App\Http\Controllers\Api\V1\ProductSellingPriceController;
use App\Http\Controllers\Api\V1\ProductsExportBarcodedController;
use App\Http\Controllers\Api\V1\ProductsExportController;
use App\Http\Controllers\Api\V1\ProductsExportMissingBarcodeController;
use App\Http\Controllers\Api\V1\ProductsExportMissingSellingPriceController;
use App\Http\Controllers\Api\V1\ProductsExportSelectedController;
use App\Http\Controllers\Api\V1\ProductsRecrawlSelectedController;
use App\Http\Controllers\Api\V1\ProductTypeBackfillController;
use App\Http\Controllers\Api\V1\ProductTypeRecomputeController;
use App\Http\Controllers\Api\V1\PurchaseOrderApplyInventoryCheckController;
use App\Http\Controllers\Api\V1\PurchaseOrderApplyReceivedToAvailableController;
use App\Http\Controllers\Api\V1\PurchaseOrderDeleteController;
use App\Http\Controllers\Api\V1\PurchaseOrderDraftAddProductsController;
use App\Http\Controllers\Api\V1\PurchaseOrderDraftCreateFromProductsController;
use App\Http\Controllers\Api\V1\PurchaseOrderDraftLinesExportController;
use App\Http\Controllers\Api\V1\PurchaseOrderFilterOptionsController;
use App\Http\Controllers\Api\V1\PurchaseOrderImportController;
use App\Http\Controllers\Api\V1\PurchaseOrderIndexController;
use App\Http\Controllers\Api\V1\PurchaseOrderItemsBulkUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderItemUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderShowController;
use App\Http\Controllers\Api\V1\PurchaseOrderUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderWorkflowChecklistUpdateController;
use App\Http\Controllers\Api\V1\ShopifyContentExportDownloadController;
use App\Http\Controllers\Api\V1\ShopifyContentExportPrepareController;
use App\Http\Controllers\Api\V1\ShopifyContentNoInventoryExportPrepareController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStartController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStatusController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStopController;
use App\Http\Controllers\Api\V1\TcgEventsIndexController;
use App\Http\Controllers\Api\V1\TcgEventsRefreshController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')
    ->group(function (): void {
        Route::get('/products', [ProductsController::class, 'index']);
        Route::get('/products/export', ProductsExportController::class);
        Route::post('/products/export/selected', ProductsExportSelectedController::class);
        Route::post('/products/recrawl/selected', ProductsRecrawlSelectedController::class);
        Route::get('/products/export/missing-barcode', ProductsExportMissingBarcodeController::class);
        Route::get('/products/export/barcoded', ProductsExportBarcodedController::class);
        Route::get('/products/export/missing-selling-price', ProductsExportMissingSellingPriceController::class);
        Route::get('/products/filter-options', ProductFilterOptionsController::class);
        Route::get('/products/replenishment/preview', ProductReplenishmentPreviewController::class);
        Route::get('/products/replenishment/export', ProductReplenishmentExportController::class);
        Route::post('/products', [ProductsController::class, 'store']);
        Route::patch('/products/{id}', [ProductsController::class, 'update'])->whereUuid('id');
        Route::patch('/products/{id}/barcode', ProductBarcodeController::class)->whereUuid('id');
        Route::patch('/products/{id}/filled', ProductFilledController::class)->whereUuid('id');
        Route::patch('/products/{id}/available', ProductAvailableController::class)->whereUuid('id');
        Route::patch('/products/{id}/maintain', ProductMaintainController::class)->whereUuid('id');
        Route::patch('/products/{id}/ready', ProductReadyController::class)->whereUuid('id');
        Route::patch('/products/{id}/latest-arrival', ProductLatestArrivalController::class)->whereUuid('id');
        Route::put('/products/{id}/selling-price', ProductSellingPriceController::class)->whereUuid('id');
        Route::get('/products/{id}/po-lines', ProductPoLinesController::class)->whereUuid('id');
        Route::post('/products/sync-missing-info', ProductMissingInfoSyncController::class);
        Route::get('/job-batches', JobBatchIndexController::class);
        Route::get('/job-batches/{id}', JobBatchShowController::class);
        Route::get('/job-batches/{id}/items', JobBatchItemsController::class);
        Route::post('/job-batches/{id}/cancel', JobBatchCancelController::class);
        Route::post('/job-batches/{id}/resume', JobBatchResumeController::class);
        Route::post('/products/{id}/plamod/sync', ProductPlamodSyncController::class)->whereUuid('id');
        Route::post('/products/{id}/product-info/sync', ProductInfoSyncController::class)->whereUuid('id');
        Route::get('/products/{id}/product-info', ProductInfoShowController::class)->whereUuid('id');
        Route::patch('/products/{id}/preferred-description-source', ProductPreferredDescriptionSourceController::class)->whereUuid('id');
        Route::get('/products/{id}/plamod', ProductPlamodShowController::class)->whereUuid('id');
        Route::put('/products/{id}/plamod/assets/order', ProductPlamodAssetOrderController::class)->whereUuid('id');
        Route::put('/products/{id}/assets/order', ProductImageAssetOrderController::class)->whereUuid('id');
        Route::post('/products/{id}/assets/manual-upload', ProductManualImageUploadController::class)->whereUuid('id');
        Route::get('/product-assets/{id}/download', ProductExternalAssetDownloadController::class)->whereNumber('id');
        Route::get('/product-assets/{id}/view', ProductExternalAssetViewController::class)->whereNumber('id');
        Route::delete('/product-assets/{id}', ProductExternalAssetDestroyController::class)->whereNumber('id');
        Route::patch('/product-assets/{id}/shopify-enabled', ProductExternalAssetShopifyEnabledController::class)->whereNumber('id');
        Route::post('/products/import', ProductImportController::class);
        Route::post('/products/import-inventory', ProductInventoryImportController::class);
        Route::post('/products/import-inventory-qty-override', ProductInventoryQuantityOverrideImportController::class);
        Route::post('/products/import-handles', ProductHandleImportController::class);
        Route::post('/products/import-inventory-check', InventoryCheckImportController::class);
        Route::post('/purchase-orders/import', PurchaseOrderImportController::class);
        Route::post('/purchase-orders/drafts/create-from-products', PurchaseOrderDraftCreateFromProductsController::class);
        Route::get('/purchase-orders/filter-options', PurchaseOrderFilterOptionsController::class);
        Route::get('/purchase-orders', PurchaseOrderIndexController::class);
        Route::get('/purchase-orders/{id}', PurchaseOrderShowController::class)->whereUuid('id');
        Route::get('/purchase-orders/{id}/draft-lines-export', PurchaseOrderDraftLinesExportController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}', PurchaseOrderUpdateController::class)->whereUuid('id');
        Route::post('/purchase-orders/{id}/draft-products', PurchaseOrderDraftAddProductsController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}/items', PurchaseOrderItemsBulkUpdateController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}/workflow-checklist', PurchaseOrderWorkflowChecklistUpdateController::class)->whereUuid('id');
        Route::post('/purchase-orders/{id}/apply-received-to-available', PurchaseOrderApplyReceivedToAvailableController::class)->whereUuid('id');
        Route::post('/purchase-orders/{id}/apply-inventory-check', PurchaseOrderApplyInventoryCheckController::class)->whereUuid('id');
        Route::delete('/purchase-orders/{id}', PurchaseOrderDeleteController::class)->whereUuid('id');
        Route::patch('/purchase-order-items/{id}', PurchaseOrderItemUpdateController::class)->whereNumber('id');
        Route::get('/inventory-check', InventoryCheckIndexController::class);
        Route::delete('/inventory-check/{id}', InventoryCheckDeleteController::class)->whereUuid('id');
        Route::get('/inventory-check/{id}', InventoryCheckShowController::class)->whereUuid('id');
        Route::get('/inventory-check/{id}/download', InventoryCheckDownloadController::class)->whereUuid('id');
        Route::post('/inventory-check/{id}/apply', InventoryCheckApplyController::class)->whereUuid('id');
        Route::patch('/inventory-check/{id}/items/{lineId}', InventoryCheckItemUpdateController::class)
            ->whereUuid('id')
            ->whereNumber('lineId');
        Route::post('/inventory-check/employee/sessions', [EmployeeInventoryCountController::class, 'createSession']);
        Route::get('/inventory-check/employee/sessions/{id}', [EmployeeInventoryCountController::class, 'showSession'])->whereUuid('id');
        Route::post('/inventory-check/employee/sessions/{id}/scan', [EmployeeInventoryCountController::class, 'scan'])->whereUuid('id');
        Route::post('/inventory-check/employee/sessions/{id}/flag-issue', [EmployeeInventoryCountController::class, 'flagIssue'])->whereUuid('id');
        Route::patch('/inventory-check/employee/sessions/{id}/lines/{lineId}', [EmployeeInventoryCountController::class, 'updateLine'])
            ->whereUuid('id')
            ->whereNumber('lineId');
        Route::delete('/inventory-check/employee/sessions/{id}/lines/{lineId}', [EmployeeInventoryCountController::class, 'removeLine'])
            ->whereUuid('id')
            ->whereNumber('lineId');

        Route::get('/shopify/image-tunnel', ShopifyImageTunnelStatusController::class);
        Route::post('/shopify/image-tunnel/start', ShopifyImageTunnelStartController::class);
        Route::post('/shopify/image-tunnel/stop', ShopifyImageTunnelStopController::class);

        Route::post('/products/exports/shopify-content/prepare', ShopifyContentExportPrepareController::class);
        Route::post('/products/exports/shopify-content-no-inventory/prepare', ShopifyContentNoInventoryExportPrepareController::class);
        Route::get('/products/exports/shopify-content/download/{exportId}', ShopifyContentExportDownloadController::class);
        Route::post('/products/backfill-types', ProductTypeBackfillController::class);
        Route::post('/products/recompute-types', ProductTypeRecomputeController::class);
        Route::post('/products/bulk-delete', ProductBulkDeleteController::class);
        Route::post('/products/bulk-archive', ProductBulkArchiveController::class);
        Route::post('/products/bulk-update', ProductBulkUpdateController::class);
        Route::post('/products/bulk/plamod-assets/rename', ProductBulkPlamodAssetRenameController::class);
        Route::delete('/products', [ProductMaintenanceController::class, 'flush']);

        Route::get('/maintenance/notes', MaintenanceNoteController::class);
        Route::put('/maintenance/notes', MaintenanceNoteUpsertController::class);
        Route::get('/maintenance/db-backups', DatabaseBackupIndexController::class);
        Route::post('/maintenance/db-backups', DatabaseBackupCreateController::class);
        Route::post('/maintenance/db-backups/restore', DatabaseBackupRestoreController::class);
        Route::post('/maintenance/refresh-latest-costs', LatestProductCostsRefreshController::class);
        Route::get('/maintenance/external-rate-limit', ExternalRateLimitShowController::class);
        Route::put('/maintenance/external-rate-limit', ExternalRateLimitUpdateController::class);
        Route::get('/maintenance/external-access', ExternalAccessShowController::class);
        Route::put('/maintenance/external-access', ExternalAccessUpdateController::class);

        Route::get('/price-research/filter-options', PriceResearchFilterOptionsController::class);
        Route::get('/price-research/products', PriceResearchProductsController::class);
        Route::delete('/price-research/products/{id}/quotes/{siteKey}', PriceResearchQuoteMaintenanceController::class)->whereUuid('id');
        Route::get('/price-research/reports', [PriceResearchQuoteReportsController::class, 'index']);
        Route::post('/price-research/reports', [PriceResearchQuoteReportsController::class, 'store']);
        Route::patch('/price-research/reports/{id}/handled', PriceResearchQuoteReportHandledController::class)->whereNumber('id');
        Route::post('/price-research/run', PriceResearchRunController::class);
        Route::post('/price-research/aliexpress/cookies', [AliExpressCookiesController::class, 'store']);
        Route::post('/price-research/runs/reset', PriceResearchRunMaintenanceController::class);
        Route::get('/price-research/runs/latest', [PriceResearchRunStatusController::class, 'latest']);
        Route::get('/price-research/runs/{id}', [PriceResearchRunStatusController::class, 'show'])->whereUuid('id');
        Route::get('/price-research/runs/{id}/logs', PriceResearchRunLogsController::class)->whereUuid('id');

        Route::get('/tcg/events', TcgEventsIndexController::class);
        Route::post('/tcg/events/refresh', TcgEventsRefreshController::class);
    });
