<?php

declare(strict_types=1);

use App\Http\Controllers\Api\V1\MaintenanceNoteController;
use App\Http\Controllers\Api\V1\MaintenanceNoteUpsertController;
use App\Http\Controllers\Api\V1\PriceResearchFilterOptionsController;
use App\Http\Controllers\Api\V1\PriceResearchProductsController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteMaintenanceController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteReportHandledController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteReportsController;
use App\Http\Controllers\Api\V1\PriceResearchRunController;
use App\Http\Controllers\Api\V1\PriceResearchRunLogsController;
use App\Http\Controllers\Api\V1\PriceResearchRunMaintenanceController;
use App\Http\Controllers\Api\V1\PriceResearchRunStatusController;
use App\Http\Controllers\Api\V1\ProductBulkDeleteController;
use App\Http\Controllers\Api\V1\ProductBulkUpdateController;
use App\Http\Controllers\Api\V1\ProductBulkPlamodAssetRenameController;
use App\Http\Controllers\Api\V1\ProductBarcodeController;
use App\Http\Controllers\Api\V1\ProductAvailableController;
use App\Http\Controllers\Api\V1\ProductFilledController;
use App\Http\Controllers\Api\V1\ProductFilterOptionsController;
use App\Http\Controllers\Api\V1\ProductImportController;
use App\Http\Controllers\Api\V1\ProductInventoryImportController;
use App\Http\Controllers\Api\V1\ProductHandleImportController;
use App\Http\Controllers\Api\V1\InventoryCheckImportController;
use App\Http\Controllers\Api\V1\InventoryCheckIndexController;
use App\Http\Controllers\Api\V1\InventoryCheckShowController;
use App\Http\Controllers\Api\V1\InventoryCheckDownloadController;
use App\Http\Controllers\Api\V1\PurchaseOrderImportController;
use App\Http\Controllers\Api\V1\PurchaseOrderIndexController;
use App\Http\Controllers\Api\V1\PurchaseOrderShowController;
use App\Http\Controllers\Api\V1\PurchaseOrderUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderDeleteController;
use App\Http\Controllers\Api\V1\PurchaseOrderItemsBulkUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderItemUpdateController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStartController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStatusController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStopController;
use App\Http\Controllers\Api\V1\ShopifyContentExportPrepareController;
use App\Http\Controllers\Api\V1\ShopifyContentExportDownloadController;
use App\Http\Controllers\Api\V1\ProductMaintenanceController;
use App\Http\Controllers\Api\V1\ProductMissingInfoSyncController;
use App\Http\Controllers\Api\V1\JobBatchShowController;
use App\Http\Controllers\Api\V1\JobBatchIndexController;
use App\Http\Controllers\Api\V1\JobBatchCancelController;
use App\Http\Controllers\Api\V1\JobBatchItemsController;
use App\Http\Controllers\Api\V1\ProductExternalAssetDownloadController;
use App\Http\Controllers\Api\V1\ProductExternalAssetViewController;
use App\Http\Controllers\Api\V1\ProductPlamodShowController;
use App\Http\Controllers\Api\V1\ProductPlamodSyncController;
use App\Http\Controllers\Api\V1\ProductPlamodAssetOrderController;
use App\Http\Controllers\Api\V1\ProductInfoSyncController;
use App\Http\Controllers\Api\V1\ProductsController;
use App\Http\Controllers\Api\V1\ProductSellingPriceController;
use App\Http\Controllers\Api\V1\ProductsExportController;
use App\Http\Controllers\Api\V1\ProductsExportMissingBarcodeController;
use App\Http\Controllers\Api\V1\ProductsExportBarcodedController;
use App\Http\Controllers\Api\V1\ProductsExportMissingSellingPriceController;
use App\Http\Controllers\Api\V1\ProductTypeBackfillController;
use App\Http\Controllers\Api\V1\ProductTypeRecomputeController;
use App\Http\Controllers\Api\V1\AliExpressCookiesController;
use App\Http\Controllers\Api\V1\DatabaseBackupIndexController;
use App\Http\Controllers\Api\V1\DatabaseBackupCreateController;
use App\Http\Controllers\Api\V1\DatabaseBackupRestoreController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')
    ->group(function (): void {
        Route::get('/products', [ProductsController::class, 'index']);
        Route::get('/products/export', ProductsExportController::class);
        Route::get('/products/export/missing-barcode', ProductsExportMissingBarcodeController::class);
        Route::get('/products/export/barcoded', ProductsExportBarcodedController::class);
        Route::get('/products/export/missing-selling-price', ProductsExportMissingSellingPriceController::class);
        Route::get('/products/filter-options', ProductFilterOptionsController::class);
        Route::post('/products', [ProductsController::class, 'store']);
        Route::patch('/products/{id}', [ProductsController::class, 'update'])->whereUuid('id');
        Route::patch('/products/{id}/barcode', ProductBarcodeController::class)->whereUuid('id');
        Route::patch('/products/{id}/filled', ProductFilledController::class)->whereUuid('id');
        Route::patch('/products/{id}/available', ProductAvailableController::class)->whereUuid('id');
        Route::put('/products/{id}/selling-price', ProductSellingPriceController::class)->whereUuid('id');
        Route::post('/products/sync-missing-info', ProductMissingInfoSyncController::class);
        Route::get('/job-batches', JobBatchIndexController::class);
        Route::get('/job-batches/{id}', JobBatchShowController::class);
        Route::get('/job-batches/{id}/items', JobBatchItemsController::class);
        Route::post('/job-batches/{id}/cancel', JobBatchCancelController::class);
        Route::post('/products/{id}/plamod/sync', ProductPlamodSyncController::class)->whereUuid('id');
        Route::post('/products/{id}/product-info/sync', ProductInfoSyncController::class)->whereUuid('id');
        Route::get('/products/{id}/plamod', ProductPlamodShowController::class)->whereUuid('id');
        Route::put('/products/{id}/plamod/assets/order', ProductPlamodAssetOrderController::class)->whereUuid('id');
        Route::get('/product-assets/{id}/download', ProductExternalAssetDownloadController::class)->whereNumber('id');
        Route::get('/product-assets/{id}/view', ProductExternalAssetViewController::class)->whereNumber('id');
        Route::post('/products/import', ProductImportController::class);
        Route::post('/products/import-inventory', ProductInventoryImportController::class);
        Route::post('/products/import-handles', ProductHandleImportController::class);
        Route::post('/products/import-inventory-check', InventoryCheckImportController::class);
        Route::post('/purchase-orders/import', PurchaseOrderImportController::class);
        Route::get('/purchase-orders', PurchaseOrderIndexController::class);
        Route::get('/purchase-orders/{id}', PurchaseOrderShowController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}', PurchaseOrderUpdateController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}/items', PurchaseOrderItemsBulkUpdateController::class)->whereUuid('id');
        Route::delete('/purchase-orders/{id}', PurchaseOrderDeleteController::class)->whereUuid('id');
        Route::patch('/purchase-order-items/{id}', PurchaseOrderItemUpdateController::class)->whereNumber('id');
        Route::get('/inventory-check', InventoryCheckIndexController::class);
        Route::get('/inventory-check/{id}', InventoryCheckShowController::class)->whereUuid('id');
        Route::get('/inventory-check/{id}/download', InventoryCheckDownloadController::class)->whereUuid('id');

        Route::get('/shopify/image-tunnel', ShopifyImageTunnelStatusController::class);
        Route::post('/shopify/image-tunnel/start', ShopifyImageTunnelStartController::class);
        Route::post('/shopify/image-tunnel/stop', ShopifyImageTunnelStopController::class);

        Route::post('/products/exports/shopify-content/prepare', ShopifyContentExportPrepareController::class);
        Route::get('/products/exports/shopify-content/download/{exportId}', ShopifyContentExportDownloadController::class);
        Route::post('/products/backfill-types', ProductTypeBackfillController::class);
        Route::post('/products/recompute-types', ProductTypeRecomputeController::class);
        Route::post('/products/bulk-delete', ProductBulkDeleteController::class);
        Route::post('/products/bulk-update', ProductBulkUpdateController::class);
        Route::post('/products/bulk/plamod-assets/rename', ProductBulkPlamodAssetRenameController::class);
        Route::delete('/products', [ProductMaintenanceController::class, 'flush']);

        Route::get('/maintenance/notes', MaintenanceNoteController::class);
        Route::put('/maintenance/notes', MaintenanceNoteUpsertController::class);
        Route::get('/maintenance/db-backups', DatabaseBackupIndexController::class);
        Route::post('/maintenance/db-backups', DatabaseBackupCreateController::class);
        Route::post('/maintenance/db-backups/restore', DatabaseBackupRestoreController::class);

        Route::get('/price-research/filter-options', PriceResearchFilterOptionsController::class);
        Route::get('/price-research/products', PriceResearchProductsController::class);
        Route::delete('/price-research/products/{id}/quotes/{siteKey}', PriceResearchQuoteMaintenanceController::class)->whereUuid('id');
        Route::get('/price-research/reports', [PriceResearchQuoteReportsController::class, 'index']);
        Route::post('/price-research/reports', [PriceResearchQuoteReportsController::class, 'store']);
        Route::patch('/price-research/reports/{id}/handled', PriceResearchQuoteReportHandledController::class)->whereNumber('id');
        Route::post('/price-research/run', PriceResearchRunController::class);
        Route::post('/price-research/aliexpress/cookies', [AliExpressCookiesController::class, 'store']);
        Route::post('/price-research/runs/reset', PriceResearchRunMaintenanceController::class);
        Route::get('/price-research/runs/latest', [PriceResearchRunStatusController::class, 'latest']);
        Route::get('/price-research/runs/{id}', [PriceResearchRunStatusController::class, 'show'])->whereUuid('id');
        Route::get('/price-research/runs/{id}/logs', PriceResearchRunLogsController::class)->whereUuid('id');
    });
