<?php

declare(strict_types=1);

use App\Http\Controllers\Api\V1\AliExpressCookiesController;
use App\Http\Controllers\Api\V1\ClearStaleLatestArrivalController;
use App\Http\Controllers\Api\V1\DatabaseBackupCreateController;
use App\Http\Controllers\Api\V1\DatabaseBackupIndexController;
use App\Http\Controllers\Api\V1\DatabaseBackupRestoreController;
use App\Http\Controllers\Api\V1\EmployeeInventoryCountController;
use App\Http\Controllers\Api\V1\ExternalAccessShowController;
use App\Http\Controllers\Api\V1\ExternalAccessUpdateController;
use App\Http\Controllers\Api\V1\ExternalRateLimitShowController;
use App\Http\Controllers\Api\V1\ExternalRateLimitUpdateController;
use App\Http\Controllers\Api\V1\InventoryCheckApplyController;
use App\Http\Controllers\Api\V1\InventoryCheckDeleteController;
use App\Http\Controllers\Api\V1\InventoryCheckDownloadController;
use App\Http\Controllers\Api\V1\InventoryCheckImportController;
use App\Http\Controllers\Api\V1\InventoryCheckIndexController;
use App\Http\Controllers\Api\V1\InventoryCheckItemAssignProductController;
use App\Http\Controllers\Api\V1\InventoryCheckItemUpdateController;
use App\Http\Controllers\Api\V1\InventoryCheckShowController;
use App\Http\Controllers\Api\V1\InventoryCheckUpdateController;
use App\Http\Controllers\Api\V1\JobBatchCancelController;
use App\Http\Controllers\Api\V1\JobBatchIndexController;
use App\Http\Controllers\Api\V1\JobBatchItemsController;
use App\Http\Controllers\Api\V1\JobBatchResumeController;
use App\Http\Controllers\Api\V1\JobBatchShowController;
use App\Http\Controllers\Api\V1\LatestProductCostsRefreshController;
use App\Http\Controllers\Api\V1\MaintenanceNoteController;
use App\Http\Controllers\Api\V1\MaintenanceNoteUpsertController;
use App\Http\Controllers\Api\V1\PlamodInstockSyncController;
use App\Http\Controllers\Api\V1\PlamodInstockSyncStatusController;
use App\Http\Controllers\Api\V1\PlamodPreorderImageViewController;
use App\Http\Controllers\Api\V1\PlamodPreordersIndexController;
use App\Http\Controllers\Api\V1\PlamodPreordersManufacturerFiltersDiscoverController;
use App\Http\Controllers\Api\V1\PlamodPreordersManufacturerFiltersIndexController;
use App\Http\Controllers\Api\V1\PlamodPreordersManufacturerFiltersUpdateController;
use App\Http\Controllers\Api\V1\PlamodPreordersSearchLinesController;
use App\Http\Controllers\Api\V1\PlamodPreordersSettingsShowController;
use App\Http\Controllers\Api\V1\PlamodPreordersSettingsUpdateController;
use App\Http\Controllers\Api\V1\PlamodPreordersSyncController;
use App\Http\Controllers\Api\V1\PlamodPreordersSyncStatusController;
use App\Http\Controllers\Api\V1\PlamodRestockCartRunCreateController;
use App\Http\Controllers\Api\V1\PlamodRestockCartRunRecheckController;
use App\Http\Controllers\Api\V1\PlamodRestockCartRunStatusController;
use App\Http\Controllers\Api\V1\PlamodRestockDecisionBulkController;
use App\Http\Controllers\Api\V1\PlamodRestockDecisionUpsertController;
use App\Http\Controllers\Api\V1\PlamodRestockDraftPurchaseOrderCreateController;
use App\Http\Controllers\Api\V1\PlamodRestockOrderVerifyController;
use App\Http\Controllers\Api\V1\PlamodRestockOrderVerifyShowController;
use App\Http\Controllers\Api\V1\PlamodRestockProposalShowController;
use App\Http\Controllers\Api\V1\PlamodRestockReorderOverrideUpsertController;
use App\Http\Controllers\Api\V1\PlamodRestockSettingsShowController;
use App\Http\Controllers\Api\V1\PlamodRestockSettingsUpdateController;
use App\Http\Controllers\Api\V1\PriceResearchFilterOptionsController;
use App\Http\Controllers\Api\V1\PriceResearchProductsController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteMaintenanceController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteReportHandledController;
use App\Http\Controllers\Api\V1\PriceResearchQuoteReportsController;
use App\Http\Controllers\Api\V1\PriceResearchRunController;
use App\Http\Controllers\Api\V1\PriceResearchRunLogsController;
use App\Http\Controllers\Api\V1\PriceResearchRunMaintenanceController;
use App\Http\Controllers\Api\V1\PriceResearchRunStatusController;
use App\Http\Controllers\Api\V1\ProductAvailableController;
use App\Http\Controllers\Api\V1\ProductBarcodeController;
use App\Http\Controllers\Api\V1\ProductBulkArchiveController;
use App\Http\Controllers\Api\V1\ProductBulkDeleteController;
use App\Http\Controllers\Api\V1\ProductBulkPlamodAssetRenameController;
use App\Http\Controllers\Api\V1\ProductBulkUpdateController;
use App\Http\Controllers\Api\V1\ProductCriticalController;
use App\Http\Controllers\Api\V1\ProductDemandShowController;
use App\Http\Controllers\Api\V1\ProductDiscontinueController;
use App\Http\Controllers\Api\V1\ProductExternalAssetDestroyController;
use App\Http\Controllers\Api\V1\ProductExternalAssetDownloadController;
use App\Http\Controllers\Api\V1\ProductExternalAssetShopifyEnabledController;
use App\Http\Controllers\Api\V1\ProductExternalAssetThumbnailController;
use App\Http\Controllers\Api\V1\ProductExternalAssetViewController;
use App\Http\Controllers\Api\V1\ProductFilledController;
use App\Http\Controllers\Api\V1\ProductFilterOptionsController;
use App\Http\Controllers\Api\V1\ProductHandleImportController;
use App\Http\Controllers\Api\V1\ProductHazardousShipmentController;
use App\Http\Controllers\Api\V1\ProductHoldController;
use App\Http\Controllers\Api\V1\ProductImageAssetOrderController;
use App\Http\Controllers\Api\V1\ProductImportController;
use App\Http\Controllers\Api\V1\ProductInfoShowController;
use App\Http\Controllers\Api\V1\ProductInfoSyncController;
use App\Http\Controllers\Api\V1\ProductInventoryImportController;
use App\Http\Controllers\Api\V1\ProductInventoryQuantityOverrideImportController;
use App\Http\Controllers\Api\V1\ProductLatestArrivalController;
use App\Http\Controllers\Api\V1\ProductMaintainController;
use App\Http\Controllers\Api\V1\ProductMaintenanceController;
use App\Http\Controllers\Api\V1\ProductManualImageUploadController;
use App\Http\Controllers\Api\V1\ProductMissingInfoSyncController;
use App\Http\Controllers\Api\V1\ProductPlamodAssetOrderController;
use App\Http\Controllers\Api\V1\ProductPlamodShowController;
use App\Http\Controllers\Api\V1\ProductPlamodSyncController;
use App\Http\Controllers\Api\V1\ProductPoLinesController;
use App\Http\Controllers\Api\V1\ProductPreferredDescriptionSourceController;
use App\Http\Controllers\Api\V1\ProductReadyController;
use App\Http\Controllers\Api\V1\ProductReplenishmentExportController;
use App\Http\Controllers\Api\V1\ProductReplenishmentPreviewController;
use App\Http\Controllers\Api\V1\ProductsBulkPushShopifyPreviewController;
use App\Http\Controllers\Api\V1\ProductsBulkPushShopifySelectedController;
use App\Http\Controllers\Api\V1\ProductsController;
use App\Http\Controllers\Api\V1\ProductSellingPriceController;
use App\Http\Controllers\Api\V1\ProductSellingPriceHistoryController;
use App\Http\Controllers\Api\V1\ProductsExportBarcodedController;
use App\Http\Controllers\Api\V1\ProductsExportController;
use App\Http\Controllers\Api\V1\ProductsExportMissingBarcodeController;
use App\Http\Controllers\Api\V1\ProductsExportMissingSellingPriceController;
use App\Http\Controllers\Api\V1\ProductsExportSelectedController;
use App\Http\Controllers\Api\V1\ProductsFilteredExportController;
use App\Http\Controllers\Api\V1\ProductShipmentMethodController;
use App\Http\Controllers\Api\V1\ProductsRecrawlSelectedController;
use App\Http\Controllers\Api\V1\ProductTypeBackfillController;
use App\Http\Controllers\Api\V1\ProductTypeRecomputeController;
use App\Http\Controllers\Api\V1\ProductVendorController;
use App\Http\Controllers\Api\V1\PullShopifyInventoryToProductsController;
use App\Http\Controllers\Api\V1\PurchaseOrderApplyInventoryCheckController;
use App\Http\Controllers\Api\V1\PurchaseOrderApplyReceivedToAvailableController;
use App\Http\Controllers\Api\V1\PurchaseOrderCombinedPaymentCreateController;
use App\Http\Controllers\Api\V1\PurchaseOrderCombinedPaymentPreviewController;
use App\Http\Controllers\Api\V1\PurchaseOrderDeleteController;
use App\Http\Controllers\Api\V1\PurchaseOrderDraftAddProductsController;
use App\Http\Controllers\Api\V1\PurchaseOrderDraftCreateFromProductsController;
use App\Http\Controllers\Api\V1\PurchaseOrderDraftLinesExportController;
use App\Http\Controllers\Api\V1\PurchaseOrderFilterOptionsController;
use App\Http\Controllers\Api\V1\PurchaseOrderImportController;
use App\Http\Controllers\Api\V1\PurchaseOrderImportPreviewController;
use App\Http\Controllers\Api\V1\PurchaseOrderIndexController;
use App\Http\Controllers\Api\V1\PurchaseOrderItemsBulkUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderItemUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderSellingPriceHistoryController;
use App\Http\Controllers\Api\V1\PurchaseOrderShowController;
use App\Http\Controllers\Api\V1\PurchaseOrderUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderWorkflowActionController;
use App\Http\Controllers\Api\V1\PurchaseOrderWorkflowChecklistUpdateController;
use App\Http\Controllers\Api\V1\PurchaseOrderWorkflowVerifyController;
use App\Http\Controllers\Api\V1\RebuildProductDemandRollupsController;
use App\Http\Controllers\Api\V1\ShopifyContentExportDownloadController;
use App\Http\Controllers\Api\V1\ShopifyContentExportPrepareController;
use App\Http\Controllers\Api\V1\ShopifyContentNoInventoryExportPrepareController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStartController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStatusController;
use App\Http\Controllers\Api\V1\ShopifyImageTunnelStopController;
use App\Http\Controllers\Api\V1\ShopifyOrderHistoricalBackfillController;
use App\Http\Controllers\Api\V1\ShopifySettingsShowController;
use App\Http\Controllers\Api\V1\ShopifySettingsUpdateController;
use App\Http\Controllers\Api\V1\ShopifyWebhookLogIndexController;
use App\Http\Controllers\Api\V1\ShopifyWebhookLogShowController;
use App\Http\Controllers\Api\V1\StaffOrdersReportShowController;
use App\Http\Controllers\Api\V1\TcgEventsIndexController;
use App\Http\Controllers\Api\V1\TcgEventsRefreshController;
use App\Http\Controllers\Api\Webhooks\ShopifyWebhookController;
use Illuminate\Support\Facades\Route;

Route::post('webhooks/shopify', ShopifyWebhookController::class);

Route::prefix('v1')
    ->group(function (): void {
        Route::get('/products', [ProductsController::class, 'index']);
        Route::get('/products/export', ProductsExportController::class);
        Route::get('/products/export/filtered', ProductsFilteredExportController::class);
        Route::post('/products/export/selected', ProductsExportSelectedController::class);
        Route::post('/products/recrawl/selected', ProductsRecrawlSelectedController::class);
        Route::post('/products/shopify-push/preview', ProductsBulkPushShopifyPreviewController::class);
        Route::post('/products/shopify-push/selected', ProductsBulkPushShopifySelectedController::class);
        Route::get('/products/export/missing-barcode', ProductsExportMissingBarcodeController::class);
        Route::get('/products/export/barcoded', ProductsExportBarcodedController::class);
        Route::get('/products/export/missing-selling-price', ProductsExportMissingSellingPriceController::class);
        Route::get('/products/filter-options', ProductFilterOptionsController::class);
        Route::get('/products/replenishment/preview', ProductReplenishmentPreviewController::class);
        Route::get('/products/replenishment/export', ProductReplenishmentExportController::class);
        Route::post('/products', [ProductsController::class, 'store']);
        Route::patch('/products/{id}', [ProductsController::class, 'update'])->whereUuid('id');
        Route::patch('/products/{id}/barcode', ProductBarcodeController::class)->whereUuid('id');
        Route::patch('/products/{id}/filled', ProductFilledController::class)->whereUuid('id');
        Route::patch('/products/{id}/available', ProductAvailableController::class)->whereUuid('id');
        Route::patch('/products/{id}/hold', ProductHoldController::class)->whereUuid('id');
        Route::patch('/products/{id}/maintain', ProductMaintainController::class)->whereUuid('id');
        Route::patch('/products/{id}/vendor', ProductVendorController::class)->whereUuid('id');
        Route::patch('/products/{id}/ready', ProductReadyController::class)->whereUuid('id');
        Route::patch('/products/{id}/latest-arrival', ProductLatestArrivalController::class)->whereUuid('id');
        Route::patch('/products/{id}/critical', ProductCriticalController::class)->whereUuid('id');
        Route::patch('/products/{id}/discontinue', ProductDiscontinueController::class)->whereUuid('id');
        Route::patch('/products/{id}/hazardous-shipment', ProductHazardousShipmentController::class)->whereUuid('id');
        Route::patch('/products/{id}/shipment-method', ProductShipmentMethodController::class)->whereUuid('id');
        Route::put('/products/{id}/selling-price', ProductSellingPriceController::class)->whereUuid('id');
        Route::get('/products/{id}/po-lines', ProductPoLinesController::class)->whereUuid('id');
        Route::get('/products/{id}/selling-price-history', ProductSellingPriceHistoryController::class)->whereUuid('id');
        Route::post('/products/sync-missing-info', ProductMissingInfoSyncController::class);
        Route::get('/job-batches', JobBatchIndexController::class);
        Route::get('/job-batches/{id}', JobBatchShowController::class);
        Route::get('/job-batches/{id}/items', JobBatchItemsController::class);
        Route::post('/job-batches/{id}/cancel', JobBatchCancelController::class);
        Route::post('/job-batches/{id}/resume', JobBatchResumeController::class);
        Route::post('/products/{id}/plamod/sync', ProductPlamodSyncController::class)->whereUuid('id');
        Route::post('/products/{id}/product-info/sync', ProductInfoSyncController::class)->whereUuid('id');
        Route::get('/products/{id}/product-info', ProductInfoShowController::class)->whereUuid('id');
        Route::patch('/products/{id}/preferred-description-source', ProductPreferredDescriptionSourceController::class)->whereUuid('id');
        Route::get('/products/{id}/plamod', ProductPlamodShowController::class)->whereUuid('id');
        Route::put('/products/{id}/plamod/assets/order', ProductPlamodAssetOrderController::class)->whereUuid('id');
        Route::put('/products/{id}/assets/order', ProductImageAssetOrderController::class)->whereUuid('id');
        Route::post('/products/{id}/assets/manual-upload', ProductManualImageUploadController::class)->whereUuid('id');
        Route::get('/product-assets/{id}/download', ProductExternalAssetDownloadController::class)->whereNumber('id');
        Route::get('/product-assets/{id}/view', ProductExternalAssetViewController::class)->whereNumber('id');
        Route::get('/product-assets/{id}/thumb', ProductExternalAssetThumbnailController::class)->whereNumber('id');
        Route::delete('/product-assets/{id}', ProductExternalAssetDestroyController::class)->whereNumber('id');
        Route::patch('/product-assets/{id}/shopify-enabled', ProductExternalAssetShopifyEnabledController::class)->whereNumber('id');
        Route::post('/products/import', ProductImportController::class);
        Route::post('/products/import-inventory', ProductInventoryImportController::class);
        Route::post('/products/import-inventory-qty-override', ProductInventoryQuantityOverrideImportController::class);
        Route::post('/products/import-handles', ProductHandleImportController::class);
        Route::post('/products/import-inventory-check', InventoryCheckImportController::class);
        Route::post('/purchase-orders/import/preview', PurchaseOrderImportPreviewController::class);
        Route::post('/purchase-orders/import', PurchaseOrderImportController::class);
        Route::post('/purchase-orders/drafts/create-from-products', PurchaseOrderDraftCreateFromProductsController::class);
        Route::post('/purchase-orders/combined-payments/preview', PurchaseOrderCombinedPaymentPreviewController::class);
        Route::post('/purchase-orders/combined-payments', PurchaseOrderCombinedPaymentCreateController::class);
        Route::get('/purchase-orders/filter-options', PurchaseOrderFilterOptionsController::class);
        Route::get('/purchase-orders', PurchaseOrderIndexController::class);
        Route::get('/purchase-orders/{id}', PurchaseOrderShowController::class)->whereUuid('id');
        Route::get('/purchase-orders/{id}/selling-price-history', PurchaseOrderSellingPriceHistoryController::class)->whereUuid('id');
        Route::get('/purchase-orders/{id}/draft-lines-export', PurchaseOrderDraftLinesExportController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}', PurchaseOrderUpdateController::class)->whereUuid('id');
        Route::post('/purchase-orders/{id}/draft-products', PurchaseOrderDraftAddProductsController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}/items', PurchaseOrderItemsBulkUpdateController::class)->whereUuid('id');
        Route::patch('/purchase-orders/{id}/workflow-checklist', PurchaseOrderWorkflowChecklistUpdateController::class)->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-verify', PurchaseOrderWorkflowVerifyController::class)->whereUuid('id');
        Route::get('/purchase-orders/{id}/workflow-actions/export-shopify-content/preview', [PurchaseOrderWorkflowActionController::class, 'previewExportShopifyContent'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/export-shopify-content/push', [PurchaseOrderWorkflowActionController::class, 'pushExportShopifyContent'])->whereUuid('id');
        Route::get('/purchase-orders/{id}/workflow-actions/export-shopify-content/status', [PurchaseOrderWorkflowActionController::class, 'pushExportShopifyContentStatus'])->whereUuid('id');
        Route::get('/purchase-orders/{id}/workflow-actions/set-prices/preview', [PurchaseOrderWorkflowActionController::class, 'previewSetPrices'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/set-prices', [PurchaseOrderWorkflowActionController::class, 'setPrices'])->whereUuid('id');
        Route::get('/purchase-orders/{id}/workflow-actions/pull-handles/preview', [PurchaseOrderWorkflowActionController::class, 'previewPullHandles'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/pull-handles', [PurchaseOrderWorkflowActionController::class, 'pullHandles'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/prepare-inventory', [PurchaseOrderWorkflowActionController::class, 'prepareInventory'])->whereUuid('id');
        Route::get('/purchase-orders/{id}/workflow-actions/push-inventory/preview', [PurchaseOrderWorkflowActionController::class, 'previewPushInventory'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/push-inventory', [PurchaseOrderWorkflowActionController::class, 'pushInventory'])->whereUuid('id');
        Route::get('/purchase-orders/{id}/workflow-actions/push-inventory/status', [PurchaseOrderWorkflowActionController::class, 'pushInventoryStatus'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/mark-published-on-shopify', [PurchaseOrderWorkflowActionController::class, 'markPublishedOnShopify'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/mark-latest-arrival', [PurchaseOrderWorkflowActionController::class, 'markLatestArrival'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/mark-latest-arrival-published', [PurchaseOrderWorkflowActionController::class, 'markLatestArrivalPublished'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/clear-stale-latest-arrival', [PurchaseOrderWorkflowActionController::class, 'clearStaleLatestArrival'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/workflow-actions/crawl-new-products', [PurchaseOrderWorkflowActionController::class, 'crawlNewProducts'])->whereUuid('id');
        Route::post('/purchase-orders/{id}/apply-received-to-available', PurchaseOrderApplyReceivedToAvailableController::class)->whereUuid('id');
        Route::post('/purchase-orders/{id}/apply-inventory-check', PurchaseOrderApplyInventoryCheckController::class)->whereUuid('id');
        Route::delete('/purchase-orders/{id}', PurchaseOrderDeleteController::class)->whereUuid('id');
        Route::patch('/purchase-order-items/{id}', PurchaseOrderItemUpdateController::class)->whereNumber('id');
        Route::get('/inventory-check', InventoryCheckIndexController::class);
        Route::patch('/inventory-check/{id}', InventoryCheckUpdateController::class)->whereUuid('id');
        Route::delete('/inventory-check/{id}', InventoryCheckDeleteController::class)->whereUuid('id');
        Route::get('/inventory-check/{id}', InventoryCheckShowController::class)->whereUuid('id');
        Route::get('/inventory-check/{id}/download', InventoryCheckDownloadController::class)->whereUuid('id');
        Route::post('/inventory-check/{id}/apply', InventoryCheckApplyController::class)->whereUuid('id');
        Route::patch('/inventory-check/{id}/items/{lineId}', InventoryCheckItemUpdateController::class)
            ->whereUuid('id')
            ->whereNumber('lineId');
        Route::post('/inventory-check/{id}/items/{lineId}/assign-product', InventoryCheckItemAssignProductController::class)
            ->whereUuid('id')
            ->whereNumber('lineId');
        Route::post('/inventory-check/employee/sessions', [EmployeeInventoryCountController::class, 'createSession']);
        Route::get('/inventory-check/employee/sessions/{id}', [EmployeeInventoryCountController::class, 'showSession'])->whereUuid('id');
        Route::post('/inventory-check/employee/sessions/{id}/scan', [EmployeeInventoryCountController::class, 'scan'])->whereUuid('id');
        Route::post('/inventory-check/employee/sessions/{id}/flag-issue', [EmployeeInventoryCountController::class, 'flagIssue'])->whereUuid('id');
        Route::patch('/inventory-check/employee/sessions/{id}/lines/{lineId}', [EmployeeInventoryCountController::class, 'updateLine'])
            ->whereUuid('id')
            ->whereNumber('lineId');
        Route::delete('/inventory-check/employee/sessions/{id}/lines/{lineId}', [EmployeeInventoryCountController::class, 'removeLine'])
            ->whereUuid('id')
            ->whereNumber('lineId');

        Route::get('/products/{id}/demand', ProductDemandShowController::class)->whereUuid('id');

        Route::get('/shopify/webhook-logs', ShopifyWebhookLogIndexController::class);
        Route::get('/shopify/webhook-logs/{id}', ShopifyWebhookLogShowController::class)->whereNumber('id');
        Route::get('/shopify/settings', ShopifySettingsShowController::class);
        Route::put('/shopify/settings', ShopifySettingsUpdateController::class);
        Route::post('/shopify/orders/historical-backfill', ShopifyOrderHistoricalBackfillController::class);
        Route::post('/shopify/demand/rebuild-rollups', RebuildProductDemandRollupsController::class);
        Route::post('/shopify/inventory/pull-to-products', PullShopifyInventoryToProductsController::class);

        Route::get('/shopify/image-tunnel', ShopifyImageTunnelStatusController::class);
        Route::post('/shopify/image-tunnel/start', ShopifyImageTunnelStartController::class);
        Route::post('/shopify/image-tunnel/stop', ShopifyImageTunnelStopController::class);

        Route::post('/products/exports/shopify-content/prepare', ShopifyContentExportPrepareController::class);
        Route::post('/products/exports/shopify-content-no-inventory/prepare', ShopifyContentNoInventoryExportPrepareController::class);
        Route::get('/products/exports/shopify-content/download/{exportId}', ShopifyContentExportDownloadController::class);
        Route::post('/products/backfill-types', ProductTypeBackfillController::class);
        Route::post('/products/recompute-types', ProductTypeRecomputeController::class);
        Route::post('/products/bulk-delete', ProductBulkDeleteController::class);
        Route::post('/products/bulk-archive', ProductBulkArchiveController::class);
        Route::post('/products/bulk-update', ProductBulkUpdateController::class);
        Route::post('/products/bulk/plamod-assets/rename', ProductBulkPlamodAssetRenameController::class);
        Route::delete('/products', [ProductMaintenanceController::class, 'flush']);

        Route::get('/maintenance/notes', MaintenanceNoteController::class);
        Route::put('/maintenance/notes', MaintenanceNoteUpsertController::class);
        Route::get('/maintenance/db-backups', DatabaseBackupIndexController::class);
        Route::post('/maintenance/db-backups', DatabaseBackupCreateController::class);
        Route::post('/maintenance/db-backups/restore', DatabaseBackupRestoreController::class);
        Route::post('/maintenance/refresh-latest-costs', LatestProductCostsRefreshController::class);
        Route::post('/maintenance/clear-stale-latest-arrival', ClearStaleLatestArrivalController::class);
        Route::get('/maintenance/external-rate-limit', ExternalRateLimitShowController::class);
        Route::put('/maintenance/external-rate-limit', ExternalRateLimitUpdateController::class);
        Route::get('/maintenance/external-access', ExternalAccessShowController::class);
        Route::put('/maintenance/external-access', ExternalAccessUpdateController::class);

        Route::get('/reports/staff-orders', StaffOrdersReportShowController::class);

        Route::get('/price-research/filter-options', PriceResearchFilterOptionsController::class);
        Route::get('/price-research/products', PriceResearchProductsController::class);
        Route::delete('/price-research/products/{id}/quotes/{siteKey}', PriceResearchQuoteMaintenanceController::class)->whereUuid('id');
        Route::get('/price-research/reports', [PriceResearchQuoteReportsController::class, 'index']);
        Route::post('/price-research/reports', [PriceResearchQuoteReportsController::class, 'store']);
        Route::patch('/price-research/reports/{id}/handled', PriceResearchQuoteReportHandledController::class)->whereNumber('id');
        Route::post('/price-research/run', PriceResearchRunController::class);
        Route::post('/price-research/aliexpress/cookies', [AliExpressCookiesController::class, 'store']);
        Route::post('/price-research/runs/reset', PriceResearchRunMaintenanceController::class);
        Route::get('/price-research/runs/latest', [PriceResearchRunStatusController::class, 'latest']);
        Route::get('/price-research/runs/{id}', [PriceResearchRunStatusController::class, 'show'])->whereUuid('id');
        Route::get('/price-research/runs/{id}/logs', PriceResearchRunLogsController::class)->whereUuid('id');

        Route::get('/tcg/events', TcgEventsIndexController::class);
        Route::post('/tcg/events/refresh', TcgEventsRefreshController::class);

        Route::get('/preorders', PlamodPreordersIndexController::class);
        Route::post('/preorders/sync', PlamodPreordersSyncController::class);
        Route::get('/preorders/sync-status', PlamodPreordersSyncStatusController::class);
        Route::get('/preorders/settings', PlamodPreordersSettingsShowController::class);
        Route::put('/preorders/settings', PlamodPreordersSettingsUpdateController::class);
        Route::get('/preorders/manufacturer-filters', PlamodPreordersManufacturerFiltersIndexController::class);
        Route::post('/preorders/manufacturer-filters/discover', PlamodPreordersManufacturerFiltersDiscoverController::class);
        Route::put('/preorders/manufacturer-filters', PlamodPreordersManufacturerFiltersUpdateController::class);
        Route::post('/preorders/search-lines', PlamodPreordersSearchLinesController::class);
        Route::get('/preorders/{sku}/image', PlamodPreorderImageViewController::class);

        Route::get('/plamod/restock/proposal', PlamodRestockProposalShowController::class);
        Route::get('/plamod/restock/settings', PlamodRestockSettingsShowController::class);
        Route::put('/plamod/restock/settings', PlamodRestockSettingsUpdateController::class);
        Route::post('/plamod/restock/sync', PlamodInstockSyncController::class);
        Route::get('/plamod/restock/sync-status', PlamodInstockSyncStatusController::class);
        Route::post('/plamod/restock/decisions/bulk', PlamodRestockDecisionBulkController::class);
        Route::put('/plamod/restock/decisions/{sku}', PlamodRestockDecisionUpsertController::class);
        Route::put('/plamod/restock/reorder-overrides/{sku}', PlamodRestockReorderOverrideUpsertController::class);
        Route::post('/plamod/restock/draft-purchase-order', PlamodRestockDraftPurchaseOrderCreateController::class);
        Route::post('/plamod/restock/cart-run', PlamodRestockCartRunCreateController::class);
        Route::post('/plamod/restock/cart-run-recheck', PlamodRestockCartRunRecheckController::class);
        Route::get('/plamod/restock/cart-run-status', PlamodRestockCartRunStatusController::class);
        Route::post('/plamod/restock/order-verify', PlamodRestockOrderVerifyController::class);
        Route::get('/plamod/restock/order-verify', PlamodRestockOrderVerifyShowController::class);
    });
