<?php

declare(strict_types=1);

namespace App\Services\Storefront;

use App\DTOs\Storefront\ModelKitStorefrontIndexDocument;

final class ModelKitStorefrontIndexLiquidEncoder
{
    public function encode(ModelKitStorefrontIndexDocument $document): string
    {
        $json = json_encode(
            $document->toCompactArray(),
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_THROW_ON_ERROR,
        );

        return <<<LIQUID
{%- comment -%}
  Generated by pricing-tool `storefront:model-kit-index-rebuild`.
  Do not edit by hand. Git keeps an empty stub; Shopify holds the live catalog.
{%- endcomment -%}
<script type="application/json" id="ovs-mk-index-cache">
{$json}
</script>

LIQUID;
    }
}
